server:
  port: 19200
spring:
  application:
    name: plankton-auth
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 124.222.42.246:8848
        #命名空间
        namespace: plankton
      config:
        # 配置中心地址
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        #命名空间
        namespace: ${spring.cloud.nacos.discovery.namespace}
        # 配置文件格式
        file-extension: yml
